### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-write#14]
- Delete package-lock.json
- Delete yarn.lock
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by richardsaseun14** [comment]
I'm new to opensource, can I work on this?

**Comment by arshadkazmi42** [comment]
@richardsaseun14 go ahead

**Comment by arshadkazmi42** [comment]
@richardsaseun14 any updates on this?

**Comment by theerapong2425** [comment]
@พี รอบเย็น น.

**Comment by BADIA55** [comment]
مرحبا 
انا جديدة هل فعلا يمكنني ابداء بعض الحلول للمشاكل هنا,,?

**Comment by ghost** [comment]
Awesome

**Comment by garbrecht2141** [comment]
> garbrecht2
 I'am new does  anyone know when you look atyour actions,should mosts things like amazon ews be deployed already and a lot of other actions have bern deployed , except shiftsheet:) anyways whats up with that ?

**Comment by V-kremenlieva** [comment]
> Awesome

**Comment by hatrick84** [comment]
Just learning
