### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by ghost** [gh-conf/gh-conf-write#20]
Awesome

_Originally posted by @ghost in https://github.com/gh-conf/gh-conf-write/issues/14#issuecomment-806690418_

**Comment by ghost** [comment]
Wow it wasn’t ghost it was me lol

**Comment by ghost** [comment]
Dumb me ... lmao. 

Chelsea MF McCurry

**Comment by arshadkazmi42** [comment]
Spam
