### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by hatrick84** [gh-conf/gh-conf-write#21]
Recover assets

**Comment by codermakhackerone** [comment]
@hatrick84 Can you share more details, what exactly is the issue here?

**Comment by hatrick84** [comment]
I'm new, but I have investments in sites I can't get into, also was hacked on a site for 8,000 in stock.. just want to recover what's mine

**Comment by arshadkazmi42** [comment]
@hatrick84 Please post issue related to the project.
