### ISSUE TITLE
Change variable names in readme

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-write#4]
```
const configContent = await writeConf('./gh-conf-write', 'CONTENT');
console.log(configContent);
```

Change the configContent variable to `writeResult` or if you have better suggestion for the variable name
[README](https://github.com/gh-conf/gh-conf-write#usage)

**Comment by bojanadjordjevic** [comment]
Hi @arshadkazmi42  I would like to change this and contribute to this project :)

**Comment by arshadkazmi42** [comment]
Go ahead create a PR

**Comment by bojanadjordjevic** [comment]
I created pull request(this was my firs pull request)... Can you tell me
what is procedure for merging commit and closing pull request?

уто, 29. јан 2019. у 19:53 Arshad Kazmi <notifications@github.com> је
написао/ла:

**Comment by arshadkazmi42** [comment]
Reviewed and merged your PR
